<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Raft.Core/Raft.Core.csproj" />
    <ProjectReference Include="../../src/Raft.Simulation/Raft.Simulation.csproj" />
    <ProjectReference Include="../../tools/Raft.SimRun/Raft.SimRun.csproj" />
  </ItemGroup>
</Project>
